import type { Metadata } from "next";

import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/globals.scss";
import Header from "../components/Header";
import Footer from "../components/Footer";
import HeaderCenter from "@/components/HeaderCenter";
import HeaderSplit from "@/components/HeaderSplit";
import HeaderSimple from "@/components/HeaderSimple";
import FooterThreeCol from "@/components/FooterThreeCol";
import FooterFourCol from "@/components/FooterFourCol";
import FooterSimple from "@/components/FooterSimple";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Header /> */}
        {/* <HeaderCenter />
        <HeaderSplit /> */}
        <HeaderSimple />
        <main>{children}</main>
        <Footer />
        <FooterThreeCol />
        <FooterFourCol />
        <FooterSimple />
      </body>
    </html>
  );
}
